#**Project Cancer Detection**

In [5]:
import numpy as np
import pandas as pd

In [6]:
from google.colab import files
uplod_file=files.upload()

Saving breast-cancer-wisconsin.data.csv to breast-cancer-wisconsin.data.csv

In [7]:
col=['id','Clump Thickness','Unifornity of Cell Size','Unifornity of Cell Shape','Marginal Adhesion',
     'Single Epithelial Cell Size','Bare Nuclei','Bland Chromatin','Normal Nucleoli','Mitoses','Class']
df=pd.read_csv('breast-cancer-wisconsin.data.csv',names=col,header=None)
df.head()

,id,Clump Thickness,Unifornity of Cell Size,Unifornity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2

# **Data PreProcessing**

In [8]:
np.where(df.isnull())

(array([], dtype=int64), array([], dtype=int64))

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           699 non-null    int64
 1   Clump Thickness              699 non-null    int64
 2   Unifornity of Cell Size      699 non-null    int64
 3   Unifornity of Cell Shape     699 non-null    int64
 4   Marginal Adhesion            699 non-null    int64
 5   Single Epithelial Cell Size  699 non-null    int64
 6   Bare Nuclei                  699 non-null    object
 7   Bland Chromatin              699 non-null    int64
 8   Normal Nucleoli              699 non-null    int64
 9   Mitoses                      699 non-null    int64
 10  Class                        699 non-null    int64
dtypes: int64(10), object(1)
memory usage: 60.2+ KB

In [10]:
df['Bare Nuclei'].describe()

count     699
unique     11
top         1
freq      402
Name: Bare Nuclei, dtype: object

In [11]:
df['Bare Nuclei'].value_counts()

Bare Nuclei
1     402
10    132
2      30
5      30
3      28
8      21
4      19
?      16
9       9
7       8
6       4
Name: count, dtype: int64

In [14]:
df[df['Bare Nuclei']=='?']

,id,Clump Thickness,Unifornity of Cell Size,Unifornity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
23,1057013,8,4,5,1,2,?,7,3,1,4
40,1096800,6,6,6,9,6,?,7,8,1,2
139,1183246,1,1,1,1,1,?,2,1,1,2
145,1184840,1,1,3,1,2,?,2,1,1,2
158,1193683,1,1,2,1,3,?,1,1,1,2
164,1197510,5,1,1,1,2,?,3,1,1,2
235,1241232,3,1,4,1,2,?,3,1,1,2
249,169356,3,1,1,1,2,?,3,1,1,2
275,432809,3,1,3,1,2,?,2,1,1,2
292,563649,8,8,8,1,2,?,6,10,1,4
294,606140,1,1,1,1,2,?,2,1,1,2
297,61634,5,4,3,1,2,?,2,3,1,2
315,704168,4,6,5,6,7,?,4,9,1,2
321,733639,3,1,1,1,2,?,3,1,1,2
411,1238464,1,1,1,1,1,?,2,1,1,2
617,1057067,1,1,1,1,1,?,1,1,1,2

In [17]:
df['Class'].value_counts()

Class
2    458
4    241
Name: count, dtype: int64

In [23]:
df['Bare Nuclei'] = df['Bare Nuclei'].replace('?', np.nan)
df=df.dropna()

Note that for class:2 is benign ,4 is for malignant  
                                       df['class']/2-1

In [24]:
df['Bare Nuclei'].value_counts()

Bare Nuclei
1     402
10    132
2      30
5      30
3      28
8      21
4      19
9       9
7       8
6       4
Name: count, dtype: int64

In [26]:
df['Class']=df['Class']/2-1

In [27]:
df.columns

Index(['id', 'Clump Thickness', 'Unifornity of Cell Size',
       'Unifornity of Cell Shape', 'Marginal Adhesion',
       'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin',
       'Normal Nucleoli', 'Mitoses', 'Class'],
      dtype='object')

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 683 entries, 0 to 698
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           683 non-null    int64
 1   Clump Thickness              683 non-null    int64
 2   Unifornity of Cell Size      683 non-null    int64
 3   Unifornity of Cell Shape     683 non-null    int64
 4   Marginal Adhesion            683 non-null    int64
 5   Single Epithelial Cell Size  683 non-null    int64
 6   Bare Nuclei                  683 non-null    object
 7   Bland Chromatin              683 non-null    int64
 8   Normal Nucleoli              683 non-null    int64
 9   Mitoses                      683 non-null    int64
 10  Class                        683 non-null    float64
dtypes: float64(1), int64(9), object(1)
memory usage: 64.0+ KB

In [29]:
x=df.drop(['id','Class'],axis=1)
x_col=x.columns

In [30]:
y=df['Class']

In [31]:
from sklearn.preprocessing import StandardScaler

In [32]:
x=StandardScaler().fit_transform(x.values)

# Training

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
df1=pd.DataFrame(x,columns=x_col)

In [35]:
df1.head()

,Clump Thickness,Unifornity of Cell Size,Unifornity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses
0,0.197905,-0.702212,-0.741774,-0.639366,-0.555608,-0.698853,-0.181827,-0.612927,-0.3484
1,0.197905,0.277252,0.262783,0.758032,1.695166,1.772867,-0.181827,-0.285105,-0.3484
2,-0.511643,-0.702212,-0.741774,-0.639366,-0.555608,-0.424217,-0.181827,-0.612927,-0.3484
3,0.552679,1.583204,1.602192,-0.639366,-0.105454,0.125054,-0.181827,1.354008,-0.3484
4,-0.156869,-0.702212,-0.741774,0.059333,-0.555608,-0.698853,-0.181827,-0.612927,-0.3484

In [36]:
x_train,x_test,y_train,y_test=train_test_split(df1,y,train_size=0.8,random_state=42)

In [38]:
from sklearn.preprocessing import MinMaxScaler
pd.DataFrame(MinMaxScaler().fit_transform(df.drop(['id','Class'],axis=1).values),columns=x_col).head()

,Clump Thickness,Unifornity of Cell Size,Unifornity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses
0,0.444444,0.000000,0.000000,0.000000,0.111111,0.000000,0.222222,0.000000,0.0
1,0.444444,0.333333,0.333333,0.444444,0.666667,1.000000,0.222222,0.111111,0.0
2,0.222222,0.000000,0.000000,0.000000,0.111111,0.111111,0.222222,0.000000,0.0
3,0.555556,0.777778,0.777778,0.000000,0.222222,0.333333,0.222222,0.666667,0.0
4,0.333333,0.000000,0.000000,0.222222,0.111111,0.000000,0.222222,0.000000,0.0

In [39]:
from sklearn.neighbors import KNeighborsClassifier

In [40]:
knn=KNeighborsClassifier(n_neighbors=5,p=2,metric='minkowski')

In [41]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [42]:
from sklearn import preprocessing
from sklearn.model_selection import cross_val_score,cross_val_predict
from sklearn.metrics import accuracy_score,classification_report
from sklearn.metrics import roc_auc_score,confusion_matrix
def print_score(clf,x_train,x_test,y_train,y_test,train=True):
  lb=preprocessing.LabelBinarizer()
  lb.fit(y_train)
  if train:
    '''
    training performance
    '''
    res=clf.predict(x_train)
    print('Train Result:\n')
    print("acccuracy score:{0:.4f}\n".format(accuracy_score(y_train,res)))
    print("classification report:\n {}\n".format(classification_report(y_train,res)))
    print("confusion_matrix:\n{}\n".format(confusion_matrix(y_train,res)))
    print("ROC AUC:{0:.4f}\n".format(roc_auc_score(lb.transform(y_train),lb.transform(res))))
    res=cross_val_score(clf,x_train,y_train,cv=10,scoring='accuracy')
    print("Average Accuracy:\t {0:.4f}".format(np.mean(res)))
    print("Accuracy SD: \t \t{0:.4f}".format(np.std(res)))
  elif train==False:
    '''
    test performance
    '''
    res_test=clf.predict(x_test)
    print('Test Result:\n')
    print("acccuracy score:{0:.4f}\n".format(accuracy_score(y_test,res_test)))
    print("classification report:\n {}\n".format(classification_report(y_test,res_test)))
    print("confusion_matrix:\n{}\n".format(confusion_matrix(y_test,res_test)))
    print("ROC AUC:{0:.4f}\n".format(roc_auc_score(lb.transform(y_test),lb.transform(res_test))))
    res=cross_val_score(clf,x_test,y_test,cv=10,scoring='accuracy')
    print("Average Accuracy:\t {0:.4f}".format(np.mean(res_test)))
    print("Accuracy SD: \t \t{0:.4f}".format(np.std(res_test)))

In [44]:
print_score(knn,x_train,x_test,y_train,y_test,train=True)
print("\n************************************************\n")
print_score(knn,x_train,x_test,y_train,y_test,train=False)

Train Result:

acccuracy score:0.9725

classification report:
               precision    recall  f1-score   support

         0.0       0.98      0.98      0.98       365
         1.0       0.96      0.96      0.96       181

    accuracy                           0.97       546
   macro avg       0.97      0.97      0.97       546
weighted avg       0.97      0.97      0.97       546


confusion_matrix:
[[358   7]
 [  8 173]]

ROC AUC:0.9683

Average Accuracy:	 0.9634
Accuracy SD: 	 	0.0200

************************************************

Test Result:

acccuracy score:0.9562

classification report:
               precision    recall  f1-score   support

         0.0       0.94      0.99      0.96        79
         1.0       0.98      0.91      0.95        58

    accuracy                           0.96       137
   macro avg       0.96      0.95      0.95       137
weighted avg       0.96      0.96      0.96       137


confusion_matrix:
[[78  1]
 [ 5 53]]

ROC AUC:0.9506

Average Accuracy:	 0.3942
Accuracy SD: 	 	0.4887

# **Grid Search**

In [45]:
from sklearn.model_selection import GridSearchCV

In [46]:
knn.get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 5,
 'p': 2,
 'weights': 'uniform'}

In [47]:
params={'n_neighbors':[1,2,3,4,5,6,7,8,9,10]}

In [49]:
grid_search=GridSearchCV(KNeighborsClassifier(),params,n_jobs=-1,verbose=1,cv=10)

In [50]:
grid_search.fit(x_train,y_train)

Fitting 10 folds for each of 10 candidates, totalling 100 fits

GridSearchCV(cv=10, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]},
             verbose=1)

In [51]:
grid_search.best_estimator_

KNeighborsClassifier(n_neighbors=7)

In [52]:
print_score(grid_search,x_train,x_test,y_train,y_test,train=True)
print("\n************************************************\n")
print_score(grid_search,x_train,x_test,y_train,y_test,train=False)

Train Result:

acccuracy score:0.9725

classification report:
               precision    recall  f1-score   support

         0.0       0.98      0.98      0.98       365
         1.0       0.96      0.96      0.96       181

    accuracy                           0.97       546
   macro avg       0.97      0.97      0.97       546
weighted avg       0.97      0.97      0.97       546


confusion_matrix:
[[358   7]
 [  8 173]]

ROC AUC:0.9683

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Average Accuracy:	 0.9634
Accuracy SD: 	 	0.0216

************************************************

Test Result:

acccuracy score:0.9562

classification report:
               precision    recall  f1-score   support

         0.0       0.94      0.99      0.96        79
         1.0       0.98      0.91      0.95        58

    accuracy                           0.96       137
   macro avg       0.96      0.95      0.95       137
weighted avg       0.96      0.96      0.96       137


confusion_matrix:
[[78  1]
 [ 5 53]]

ROC AUC:0.9506

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Average Accuracy:	 0.3942
Accuracy SD: 	 	0.4887

In [55]:
grid_search.best_params_

{'n_neighbors': 7}

In [56]:
grid_search.cv_results_['mean_test_score']

array([0.94690236, 0.94323232, 0.96154882, 0.96521886, 0.96343434,
       0.96521886, 0.96707071, 0.96521886, 0.96521886, 0.96703704])

In [59]:
grid_search.cv_results_

{'mean_fit_time': array([0.01250443, 0.01066384, 0.01025486, 0.01055794, 0.01017666,
        0.00818167, 0.00641954, 0.00594063, 0.00956626, 0.00799551]),
 'std_fit_time': array([0.00567254, 0.00227851, 0.00159943, 0.0013956 , 0.00390113,
        0.00260249, 0.00304471, 0.00287188, 0.00437644, 0.00481713]),
 'mean_score_time': array([0.01488571, 0.01466403, 0.01592691, 0.01430748, 0.01246138,
        0.01275573, 0.00954449, 0.00922842, 0.01504955, 0.00832753]),
 'std_score_time': array([0.00752127, 0.00267164, 0.00372748, 0.00118389, 0.00306347,
        0.00370815, 0.0049172 , 0.00459636, 0.00624592, 0.00535248]),
 'param_n_neighbors': masked_array(data=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=999999),
 'params': [{'n_neighbors': 1},
  {'n_neighbors': 2},
  {'n_neighbors': 3},
  {'n_neighbors': 4},
  {'n_neighbors': 5},
  {'n_neighbors': 6},
  {'n_neighbors': 7},
  {'n_neighbors': 8},
  {'n_neighbors': 9},
  {'n_neighbors': 10}],
 'split0_test_score': array([0.90909091, 0.92727273, 0.94545455, 0.94545455, 0.94545455,
        0.94545455, 0.94545455, 0.94545455, 0.94545455, 0.94545455]),
 'split1_test_score': array([0.96363636, 0.98181818, 0.96363636, 0.98181818, 0.96363636,
        0.98181818, 0.98181818, 0.98181818, 0.98181818, 0.98181818]),
 'split2_test_score': array([0.96363636, 0.94545455, 0.98181818, 0.98181818, 0.98181818,
        0.98181818, 1.        , 1.        , 1.        , 1.        ]),
 'split3_test_score': array([0.92727273, 0.90909091, 0.94545455, 0.94545455, 0.92727273,
        0.94545455, 0.92727273, 0.92727273, 0.92727273, 0.94545455]),
 'split4_test_score': array([0.94545455, 0.96363636, 0.96363636, 0.94545455, 0.96363636,
        0.94545455, 0.96363636, 0.94545455, 0.94545455, 0.94545455]),
 'split5_test_score': array([0.96363636, 0.92727273, 0.96363636, 0.98181818, 0.96363636,
        0.98181818, 0.96363636, 0.98181818, 0.98181818, 0.98181818]),
 'split6_test_score': array([0.96296296, 0.94444444, 0.96296296, 0.98148148, 0.98148148,
        0.98148148, 0.98148148, 0.96296296, 0.96296296, 0.96296296]),
 'split7_test_score': array([0.96296296, 0.96296296, 0.98148148, 0.98148148, 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ]),
 'split8_test_score': array([0.94444444, 0.94444444, 0.94444444, 0.94444444, 0.94444444,
        0.94444444, 0.94444444, 0.94444444, 0.94444444, 0.94444444]),
 'split9_test_score': array([0.92592593, 0.92592593, 0.96296296, 0.96296296, 0.96296296,
        0.94444444, 0.96296296, 0.96296296, 0.96296296, 0.96296296]),
 'mean_test_score': array([0.94690236, 0.94323232, 0.96154882, 0.96521886, 0.96343434,
        0.96521886, 0.96707071, 0.96521886, 0.96521886, 0.96703704]),
 'std_test_score': array([0.01902405, 0.02068075, 0.01279   , 0.01721658, 0.01998151,
        0.0208227 , 0.02279777, 0.02373489, 0.02373489, 0.02133333]),
 'rank_test_score': array([ 9, 10,  8,  3,  7,  6,  1,  3,  3,  2], dtype=int32)}

# SVM,Random Forest,XGBoost

In [61]:
from sklearn import svm
clf=svm.SVC(kernel='rbf')
clf.fit(x_train,y_train)
print_score(grid_search,x_train,x_test,y_train,y_test,train=True)
print("\n************************************************\n")
print_score(grid_search,x_train,x_test,y_train,y_test,train=False)

Train Result:

acccuracy score:0.9725

classification report:
               precision    recall  f1-score   support

         0.0       0.98      0.98      0.98       365
         1.0       0.96      0.96      0.96       181

    accuracy                           0.97       546
   macro avg       0.97      0.97      0.97       546
weighted avg       0.97      0.97      0.97       546


confusion_matrix:
[[358   7]
 [  8 173]]

ROC AUC:0.9683

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Average Accuracy:	 0.9634
Accuracy SD: 	 	0.0216

************************************************

Test Result:

acccuracy score:0.9562

classification report:
               precision    recall  f1-score   support

         0.0       0.94      0.99      0.96        79
         1.0       0.98      0.91      0.95        58

    accuracy                           0.96       137
   macro avg       0.96      0.95      0.95       137
weighted avg       0.96      0.96      0.96       137


confusion_matrix:
[[78  1]
 [ 5 53]]

ROC AUC:0.9506

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Average Accuracy:	 0.3942
Accuracy SD: 	 	0.4887

In [63]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(random_state=42,n_estimators=100)
clf.fit(x_train,y_train)
print_score(grid_search,x_train,x_test,y_train,y_test,train=True)
print("\n************************************************\n")
print_score(grid_search,x_train,x_test,y_train,y_test,train=False)

Train Result:

acccuracy score:0.9725

classification report:
               precision    recall  f1-score   support

         0.0       0.98      0.98      0.98       365
         1.0       0.96      0.96      0.96       181

    accuracy                           0.97       546
   macro avg       0.97      0.97      0.97       546
weighted avg       0.97      0.97      0.97       546


confusion_matrix:
[[358   7]
 [  8 173]]

ROC AUC:0.9683

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Average Accuracy:	 0.9634
Accuracy SD: 	 	0.0216

************************************************

Test Result:

acccuracy score:0.9562

classification report:
               precision    recall  f1-score   support

         0.0       0.94      0.99      0.96        79
         1.0       0.98      0.91      0.95        58

    accuracy                           0.96       137
   macro avg       0.96      0.95      0.95       137
weighted avg       0.96      0.96      0.96       137


confusion_matrix:
[[78  1]
 [ 5 53]]

ROC AUC:0.9506

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Average Accuracy:	 0.3942
Accuracy SD: 	 	0.4887

In [65]:
import xgboost as xgb
xgb_clf=xgb.XGBClassifier(max_depth=5,n_estimators=1000,learning_rate=0.3,n_jobs=-1)
xgb_clf.fit(x_train,y_train)
print_score(grid_search,x_train,x_test,y_train,y_test,train=True)
print("\n************************************************\n")
print_score(grid_search,x_train,x_test,y_train,y_test,train=False)

Train Result:

acccuracy score:0.9725

classification report:
               precision    recall  f1-score   support

         0.0       0.98      0.98      0.98       365
         1.0       0.96      0.96      0.96       181

    accuracy                           0.97       546
   macro avg       0.97      0.97      0.97       546
weighted avg       0.97      0.97      0.97       546


confusion_matrix:
[[358   7]
 [  8 173]]

ROC AUC:0.9683

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Average Accuracy:	 0.9634
Accuracy SD: 	 	0.0216

************************************************

Test Result:

acccuracy score:0.9562

classification report:
               precision    recall  f1-score   support

         0.0       0.94      0.99      0.96        79
         1.0       0.98      0.91      0.95        58

    accuracy                           0.96       137
   macro avg       0.96      0.95      0.95       137
weighted avg       0.96      0.96      0.96       137


confusion_matrix:
[[78  1]
 [ 5 53]]

ROC AUC:0.9506

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Fitting 10 folds for each of 10 candidates, totalling 100 fits
Average Accuracy:	 0.3942
Accuracy SD: 	 	0.4887